name: train
mode: train

resume: false
finetune: false

# batch size for each GPU
batch_size: 128
epochs: 1000

freeze: []

optimizer:
  lr: 1e-3
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 1e-2
  
  monitor_val: val_MAE
  patience: 100
  factor: 0.1
  threshold: 0.01

  grad_clip_value: 0
    
model:
  input_dim: 10
  output_dim: 1
  hidden_dim: 64